name: maxHearts
main: com.maxhearts.MaxHeartsPlugin
version: 1.1.0
api-version: '1.21'

commands:
  maxhearts:
    description: Manage player max hearts (set/give/take/donate/transfer/get)
    usage: |
      /maxhearts set <player|uuid> <hearts>
      /maxhearts give <player|uuid> <amount>
      /maxhearts take <player|uuid> <amount>
      /maxhearts donate <player|uuid> <amount>
      /maxhearts transfer <fromPlayer|uuid> <toPlayer|uuid> <amount>
      /maxhearts get <player|uuid>
    aliases: [mh]
    permission: maxhearts.use
  sethearts:
    description: Set a player's hearts (legacy alias)
    usage: /sethearts <player|uuid> <hearts>
    permission: maxhearts.set

permissions:
  maxhearts.use:
    default: op
  maxhearts.set:
    default: op
  maxhearts.give:
    default: op
  maxhearts.take:
    default: op
  maxhearts.donate:
    default: true
  maxhearts.transfer:
    default: op
